### ISSUE TITLE
Suggesting you to add commenting option on your site

### ISSUE THREAD

**Issue by anomepani** [Daniel-Krzyczkowski/Daniel-Krzyczkowski.github.io#4]
Recently I found your blog while researching on Azure B2C Custom Policy and found other blog posts very useful on Azure DevOps and different azure service.

If a comment is allowed on the blog post, It's a very good place to ask queries and share knowledge.

I have doubt for one article which shows separate azure key vault for each app environment, for this kind of scenario, what is the best way or best practice to deploy database related changes in each environment.

How can be ensure CI CD Pipeline for DB Related changes?

**Comment by Daniel-Krzyczkowski** [comment]
Hi, thank you for your suggestion, I will think about it. I also noticed that if people have specific questions, they either ask them on Twitter directly or using LinkedIn messages.
When it comes it your question. Please see my answer below - if you will have more questions, let's discuss them here.

Let's assume that you have three environments: DEV, TEST and PROD.
Each of these environments contains database (let's assume that this is Azure SQL relational database). Then, each of these databases has own connection string and credentials in general. You should store these credentials/connection strings in the Azure Key Vault (created per each environment).
Then in Azure DevOps you can link these secrets from the Azure Key Vault in the Variable groups.
Now when it comes to database updates you have two possibilities:
1. [Using DACPAC](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/azure-sqldb?view=azure-devops&tabs=yaml)
2. Using [migrations](https://medium.com/vx-company/entityframeworkcore-code-first-migrations-in-azure-devops-b5eb845fce18) if you use Entity Framework Core in you application. Then you can apply them in the pipelines in Azure DevOps for each environment.

Generally speaking it is good idea to use Azure DevOps pipelines to with templates and inject parameters from the Variable Groups to apply changes on each environment. Please let me know if it helped somehow.
