### ISSUE TITLE
Extract email or read email from Azure AD B2C with Signup and SignIn using Username custom policy?

### ISSUE THREAD

**Issue by anomepani** [Daniel-Krzyczkowski/Daniel-Krzyczkowski.github.io#5]
I have reviewed your article on Azure AD B2C with [Signup Sign In using Email flow](https://daniel-krzyczkowski.github.io/Azure-AD-B2C-Series-Custom-Policies-With-Custom-Claims/) with a custom policy which is very good with content.

I am exploring Signup and SignIn using username only and configuring MFA using Email, I have researched and explored different policy but don't know which policy will work.

I am also facing issues while reading emails after user logged in using Username and password?

If you give light on this it will be very helpful.

**Comment by Daniel-Krzyczkowski** [comment]
I will try to help.

1. I added[ custom policies templates with MFA](https://github.com/Daniel-Krzyczkowski/IdentityDeveloperTemplates/tree/master/src/ad-b2c-templates/ad-b2c-custom-policies-mfa-enabled/custom-policies) enabled to my Identity Developer Templates repository
2. If you want to read user email after login you have to use below output claim:
`<OutputClaim ClaimTypeReferenceId="signInNames.emailAddress" PartnerClaimType="email" />`
Above line is used in my sign in/sign up policy:

```
  <RelyingParty>
    <DefaultUserJourney ReferenceId="SignUpOrSignInWithUsername" />
    <TechnicalProfile Id="PolicyProfile">
      <DisplayName>PolicyProfile</DisplayName>
      <Protocol Name="OpenIdConnect" />
      <OutputClaims>
        <OutputClaim ClaimTypeReferenceId="displayName" />
        <OutputClaim ClaimTypeReferenceId="givenName" />
        <OutputClaim ClaimTypeReferenceId="surname" />
        <OutputClaim ClaimTypeReferenceId="signInNames.emailAddress" PartnerClaimType="email" />
        <OutputClaim ClaimTypeReferenceId="objectId" PartnerClaimType="sub" />
        <OutputClaim ClaimTypeReferenceId="signinname" />
      </OutputClaims>
      <SubjectNamingInfo ClaimType="sub" />
    </TechnicalProfile>
  </RelyingParty>
```

Please let me know if it helped.

**Comment by anomepani** [comment]
Thanks for your reply and help.

**Comment by anomepani** [comment]
@Daniel-Krzyczkowski , I have reviewed your custom policy for MFA using Phone, I am trying to configure MFA using email and but it always prompting MFA  for email-based MFA configuration.

I am not sure how to configure the MFA session for email-based MFA.

In case if you have any thought let me know
Thanks in advance for any suggestions.
